/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalpbogame;

import javax.swing.*;
import java.awt.event.ActionEvent;

public class ClassPlayer extends javax.swing.JFrame {
    private PlayerStatus playerStatus;    
    private Character character;
    private String userName;
    public int HPSorc = 15;
    public int ATKSorc = 12;
    public int DEFSorc = 5;
    public int HPBard = 15;
    public int ATKBard = 10;
    public int DEFBard = 7;
    public int HPBarb = 20;
    public int ATKBarb = 10;
    public int DEFBarb = 5;

    public ClassPlayer(String NameSelect) {
        this.userName = NameSelect;
        initComponents();
        setVisible(true);
        playerStatus = new PlayerStatus(" ");
    }
    public void initComponents(String NameSelect){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Choose Your Character");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 420, 50));

        jButton5.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 110, 40));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HP is increased by 5 than Normal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 220, 30));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DEF increased by 2 than Normal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 220, 30));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ATK increased by 2 than Normal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 220, 30));

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Weapon: Axe");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 180, 30));

        jLabel7.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Weapon: Lyre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, 30));

        jLabel6.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Weapon: Staff");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 30));

        jButton4.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jButton4.setText("Barbarian");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PixelBackgrounds/Barb.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 160, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PixelBackgrounds/Bard.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 210, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PixelBackgrounds/Sorc.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 180));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose Your Character");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 420, 50));

        jButton2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jButton2.setText("Sorcerer");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 40));

        jButton3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jButton3.setText("Bard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PixelBackgrounds/Pixel7.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 660, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void GoToBattleGame(Character character){
        Battlegame battlegame = new Battlegame(character);
        battlegame.setVisible(true);
        battlegame.pack();
        battlegame.setLocationRelativeTo(null);
        battlegame.setDefaultCloseOperation(Battlegame.EXIT_ON_CLOSE);
        this.dispose();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        playerStatus.chooseSorcerer();
        character = new Character(userName,playerStatus.getHPSorc(), playerStatus.getATKSorc(),playerStatus.getDEFSorc());
        updatePlayerInfoSorcerer();
        GoToBattleGame(character);
        //simpan data
        DataSave p =new DataSave();
        p.Simpan(userName, String.valueOf(HPSorc), String.valueOf(ATKSorc), String.valueOf(DEFSorc));
    }
        public void updatePlayerInfoSorcerer() {
        JOptionPane.showMessageDialog(this, "Player Name: " + userName +
                "\nBase Health: " + playerStatus.getHPSorc()+
                "\nBase Attack: " + playerStatus.getATKSorc()+
                "\nBase Defense: " + playerStatus.getDEFSorc());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        playerStatus.chooseBard();
        character = new Character(userName,playerStatus.getHPBard(), playerStatus.getATKBard(),playerStatus.getDEFBard());
        updatePlayerInfoBard();
        GoToBattleGame(character);
        //simpan data
        DataSave p =new DataSave();
        p.Simpan(userName, String.valueOf(HPBard), String.valueOf(ATKBard), String.valueOf(DEFBard));
    }
        public void updatePlayerInfoBard() {
        JOptionPane.showMessageDialog(this, "Player Name: " + userName +
                "\nBase Health: " + playerStatus.getHPBard()+
                "\nBase Attack: " + playerStatus.getATKBard()+
                "\nBase Defense: " + playerStatus.getDEFBard());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        playerStatus.chooseBarbarian();
        character = new Character(userName,playerStatus.getHPBarb(), playerStatus.getATKBarb(),playerStatus.getDEFBarb());
        updatePlayerInfoBarbarian();
        GoToBattleGame(character);
        //simpan data
        DataSave p =new DataSave();
        p.Simpan(userName, String.valueOf(HPBarb), String.valueOf(ATKBarb), String.valueOf(DEFBarb));
    }
        public void updatePlayerInfoBarbarian() {
        JOptionPane.showMessageDialog(this, "Player Name: " + userName +
                "\nBase Health: " + playerStatus.getHPBarb()+
                "\nBase Attack: " + playerStatus.getATKBarb()+
                "\nBase Defense: " + playerStatus.getDEFBarb());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassPlayer("DefaultName").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
